version: 1
services:
  - type: web
    name: JFSDProject
    env: java
    buildCommand: ./build.sh
    startCommand: java -jar target/JFSDProject.jar
    autoDeploy: true
    envVars:
      - key: MAVEN_VERSION
        value: 3.8.4  # Specify your required Maven version here
