version: 1
services:
  - type: web
    name: JFSDProject
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar target/JFSDProject.jar
    autoDeploy: true
    envVars:
      - key: JAVA_VERSION
        value: "11"  # Adjust to your required Java version
      - key: MAVEN_VERSION
        value: "3.8.4"  # Adjust to your required Maven version
